[package]
name = "hello-rust"
version = "0.2.0"
authors = ["youngday"]
edition = "2018"
# Cargo功能解析器
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
log = "0.4.8"
env_logger = "0.8.3"

