[package]
name = "demo"
version = "0.3.0"
authors = ["youngday"]
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
tokio = { version = "1.21", features = ["full", "tracing"] }
tokio-util = { version = "0.7", features = ["full"] }
tokio-stream = { version = "0.1" }
reqwest = { version = "0.11", features = ["json"] }
