[package]
name = "demo"
version = "0.2.0"
authors = ["youngday"]
edition = "2018"
# Cargo功能解析器
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
log = "0.4.14"
env_logger = "0.8.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"

