[package]
name = "demo"
version = "0.3.0"
authors = ["youngday"]
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.8"
config ="0.13"
glob = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.8"
serde_yaml = "0.8"
tokio = { version = "1.21", features = ["full", "tracing"] }
tokio-util = { version = "0.7", features = ["full"] }
tokio-stream = { version = "0.1" }
reqwest = { version = "0.11", features = ["json"] }

# lazy_static = "1.4"
log4rs = {version="1.2",features = ["toml","json_encoder"]}
# async-std = { version = "1.12", features = ["attributes","tokio1"]  }
# futures="0.3"
tmq={version="0.3.2"}
